import type { PinCodeEntry } from '@/types'

export const PIN_CODE_DATA: Record<string, PinCodeEntry> = {
  // Delhi
  '110001': { city: 'New Delhi', state: 'Delhi', postOffice: 'Connaught Place' },
  '110002': { city: 'New Delhi', state: 'Delhi', postOffice: 'Ashok Road' },
  '110003': { city: 'New Delhi', state: 'Delhi', postOffice: 'Lodi Road' },
  '110004': { city: 'New Delhi', state: 'Delhi', postOffice: 'Chanakyapuri' },
  '110005': { city: 'New Delhi', state: 'Delhi', postOffice: 'Karol Bagh' },
  '110006': { city: 'New Delhi', state: 'Delhi', postOffice: 'Daryaganj' },
  '110007': { city: 'New Delhi', state: 'Delhi', postOffice: 'Civil Lines' },
  '110008': { city: 'New Delhi', state: 'Delhi', postOffice: 'Patel Nagar' },
  '110009': { city: 'New Delhi', state: 'Delhi', postOffice: 'Sadar Bazar' },
  '110010': { city: 'New Delhi', state: 'Delhi', postOffice: 'Safdarjung Enclave' },
  '110011': { city: 'New Delhi', state: 'Delhi', postOffice: 'R K Puram' },
  '110012': { city: 'New Delhi', state: 'Delhi', postOffice: 'Vasant Vihar' },
  '110013': { city: 'New Delhi', state: 'Delhi', postOffice: 'Lajpat Nagar' },
  '110014': { city: 'New Delhi', state: 'Delhi', postOffice: 'Jangpura' },
  '110015': { city: 'New Delhi', state: 'Delhi', postOffice: 'Kalkaji' },
  '110016': { city: 'New Delhi', state: 'Delhi', postOffice: 'Hauz Khas' },
  '110017': { city: 'New Delhi', state: 'Delhi', postOffice: 'Malviya Nagar' },
  '110018': { city: 'New Delhi', state: 'Delhi', postOffice: 'Tilak Nagar' },
  '110019': { city: 'New Delhi', state: 'Delhi', postOffice: 'Mehrauli' },
  '110020': { city: 'New Delhi', state: 'Delhi', postOffice: 'Vasant Kunj' },
  '110025': { city: 'New Delhi', state: 'Delhi', postOffice: 'Sarita Vihar' },
  '110030': { city: 'New Delhi', state: 'Delhi', postOffice: 'Munirka' },
  '110040': { city: 'New Delhi', state: 'Delhi', postOffice: 'Rohini' },
  '110051': { city: 'New Delhi', state: 'Delhi', postOffice: 'Shahdara' },
  '110059': { city: 'New Delhi', state: 'Delhi', postOffice: 'Dwarka' },
  '110063': { city: 'New Delhi', state: 'Delhi', postOffice: 'Janakpuri' },
  '110064': { city: 'New Delhi', state: 'Delhi', postOffice: 'Uttam Nagar' },
  '110075': { city: 'New Delhi', state: 'Delhi', postOffice: 'Vikaspuri' },
  '110085': { city: 'New Delhi', state: 'Delhi', postOffice: 'Paschim Vihar' },
  '110092': { city: 'New Delhi', state: 'Delhi', postOffice: 'Laxmi Nagar' },

  // Mumbai, Maharashtra
  '400001': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Fort' },
  '400002': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Kalbadevi' },
  '400003': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Masjid' },
  '400004': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Charni Road' },
  '400005': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Colaba' },
  '400006': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Malabar Hill' },
  '400007': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Grant Road' },
  '400008': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Reay Road' },
  '400010': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Mazgaon' },
  '400012': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Parel' },
  '400013': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Sewri' },
  '400014': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Dadar' },
  '400016': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Mahim' },
  '400018': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Worli' },
  '400019': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Sion' },
  '400022': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Kurla' },
  '400024': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Matunga' },
  '400025': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Dharavi' },
  '400028': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Santacruz West' },
  '400029': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Santacruz East' },
  '400050': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Bandra West' },
  '400051': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Bandra East' },
  '400053': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Andheri East' },
  '400058': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Andheri West' },
  '400063': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Malad East' },
  '400064': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Malad West' },
  '400067': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Borivali East' },
  '400092': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Powai' },
  '400093': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Ghatkopar East' },
  '400097': { city: 'Mumbai', state: 'Maharashtra', postOffice: 'Mulund West' },

  // Pune, Maharashtra
  '411001': { city: 'Pune', state: 'Maharashtra', postOffice: 'Pune City' },
  '411002': { city: 'Pune', state: 'Maharashtra', postOffice: 'Camp' },
  '411003': { city: 'Pune', state: 'Maharashtra', postOffice: 'Shivajinagar' },
  '411004': { city: 'Pune', state: 'Maharashtra', postOffice: 'Deccan Gymkhana' },
  '411005': { city: 'Pune', state: 'Maharashtra', postOffice: 'Model Colony' },
  '411007': { city: 'Pune', state: 'Maharashtra', postOffice: 'Kothrud' },
  '411008': { city: 'Pune', state: 'Maharashtra', postOffice: 'Swargate' },
  '411011': { city: 'Pune', state: 'Maharashtra', postOffice: 'Hadapsar' },
  '411013': { city: 'Pune', state: 'Maharashtra', postOffice: 'Yerawada' },
  '411014': { city: 'Pune', state: 'Maharashtra', postOffice: 'Ghorpadi' },
  '411028': { city: 'Pune', state: 'Maharashtra', postOffice: 'Bavdhan' },
  '411045': { city: 'Pune', state: 'Maharashtra', postOffice: 'Aundh' },
  '411057': { city: 'Pune', state: 'Maharashtra', postOffice: 'Baner' },

  // Bengaluru, Karnataka
  '560001': { city: 'Bengaluru', state: 'Karnataka', postOffice: 'Bangalore GPO' },
  '560002': { city: 'Bengaluru', state: 'Karnataka', postOffice: 'Chamarajpet' },
  '560003': { city: 'Bengaluru', state: 'Karnataka', postOffice: 'Basavanagudi' },
  '560004': { city: 'Bengaluru', state: 'Karnataka', postOffice: 'Malleswaram' },
  '560005': { city: 'Bengaluru', state: 'Karnataka', postOffice: 'Rajajinagar' },
  '560008': { city: 'Bengaluru', state: 'Karnataka', postOffice: 'Yeshwantpur' },
  '560010': { city: 'Bengaluru', state: 'Karnataka', postOffice: 'Jayanagar' },
  '560011': { city: 'Bengaluru', state: 'Karnataka', postOffice: 'J P Nagar' },
  '560017': { city: 'Bengaluru', state: 'Karnataka', postOffice: 'Vijayanagar' },
  '560027': { city: 'Bengaluru', state: 'Karnataka', postOffice: 'Banashankari' },
  '560029': { city: 'Bengaluru', state: 'Karnataka', postOffice: 'Padmanabhanagar' },
  '560034': { city: 'Bengaluru', state: 'Karnataka', postOffice: 'Koramangala' },
  '560038': { city: 'Bengaluru', state: 'Karnataka', postOffice: 'Indiranagar' },
  '560040': { city: 'Bengaluru', state: 'Karnataka', postOffice: 'HAL' },
  '560047': { city: 'Bengaluru', state: 'Karnataka', postOffice: 'Whitefield' },
  '560066': { city: 'Bengaluru', state: 'Karnataka', postOffice: 'Electronic City' },
  '560068': { city: 'Bengaluru', state: 'Karnataka', postOffice: 'Marathahalli' },
  '560076': { city: 'Bengaluru', state: 'Karnataka', postOffice: 'Hebbal' },
  '560094': { city: 'Bengaluru', state: 'Karnataka', postOffice: 'BTM Layout' },
  '560103': { city: 'Bengaluru', state: 'Karnataka', postOffice: 'HSR Layout' },

  // Chennai, Tamil Nadu
  '600001': { city: 'Chennai', state: 'Tamil Nadu', postOffice: 'Chennai GPO' },
  '600002': { city: 'Chennai', state: 'Tamil Nadu', postOffice: 'Park Town' },
  '600003': { city: 'Chennai', state: 'Tamil Nadu', postOffice: 'Chepauk' },
  '600004': { city: 'Chennai', state: 'Tamil Nadu', postOffice: 'Thousand Lights' },
  '600006': { city: 'Chennai', state: 'Tamil Nadu', postOffice: 'Chetpet' },
  '600007': { city: 'Chennai', state: 'Tamil Nadu', postOffice: 'Egmore' },
  '600010': { city: 'Chennai', state: 'Tamil Nadu', postOffice: 'Nungambakkam' },
  '600014': { city: 'Chennai', state: 'Tamil Nadu', postOffice: 'Ashok Nagar' },
  '600017': { city: 'Chennai', state: 'Tamil Nadu', postOffice: 'T Nagar' },
  '600020': { city: 'Chennai', state: 'Tamil Nadu', postOffice: 'Adyar' },
  '600032': { city: 'Chennai', state: 'Tamil Nadu', postOffice: 'Velachery' },
  '600040': { city: 'Chennai', state: 'Tamil Nadu', postOffice: 'Anna Nagar' },
  '600042': { city: 'Chennai', state: 'Tamil Nadu', postOffice: 'Ambattur' },
  '600045': { city: 'Chennai', state: 'Tamil Nadu', postOffice: 'Chromepet' },
  '600050': { city: 'Chennai', state: 'Tamil Nadu', postOffice: 'Porur' },
  '600096': { city: 'Chennai', state: 'Tamil Nadu', postOffice: 'Sholinganallur' },
  '600119': { city: 'Chennai', state: 'Tamil Nadu', postOffice: 'Perungudi' },

  // Hyderabad, Telangana
  '500001': { city: 'Hyderabad', state: 'Telangana', postOffice: 'Hyderabad GPO' },
  '500002': { city: 'Hyderabad', state: 'Telangana', postOffice: 'Abids' },
  '500003': { city: 'Hyderabad', state: 'Telangana', postOffice: 'Chikkadpally' },
  '500004': { city: 'Hyderabad', state: 'Telangana', postOffice: 'Himayatnagar' },
  '500006': { city: 'Hyderabad', state: 'Telangana', postOffice: 'Nampally' },
  '500007': { city: 'Hyderabad', state: 'Telangana', postOffice: 'Begumpet' },
  '500008': { city: 'Hyderabad', state: 'Telangana', postOffice: 'Secunderabad' },
  '500016': { city: 'Hyderabad', state: 'Telangana', postOffice: 'Kukatpally' },
  '500018': { city: 'Hyderabad', state: 'Telangana', postOffice: 'Ameerpet' },
  '500032': { city: 'Hyderabad', state: 'Telangana', postOffice: 'Jubilee Hills' },
  '500033': { city: 'Hyderabad', state: 'Telangana', postOffice: 'Banjara Hills' },
  '500034': { city: 'Hyderabad', state: 'Telangana', postOffice: 'Madhapur' },
  '500035': { city: 'Hyderabad', state: 'Telangana', postOffice: 'Gachibowli' },
  '500036': { city: 'Hyderabad', state: 'Telangana', postOffice: 'Film Nagar' },
  '500081': { city: 'Hyderabad', state: 'Telangana', postOffice: 'Kondapur' },
  '500084': { city: 'Hyderabad', state: 'Telangana', postOffice: 'HITEC City' },

  // Kolkata, West Bengal
  '700001': { city: 'Kolkata', state: 'West Bengal', postOffice: 'Dalhousie' },
  '700006': { city: 'Kolkata', state: 'West Bengal', postOffice: 'Shyambazar' },
  '700007': { city: 'Kolkata', state: 'West Bengal', postOffice: 'Ultadanga' },
  '700009': { city: 'Kolkata', state: 'West Bengal', postOffice: 'Sinthee' },
  '700012': { city: 'Kolkata', state: 'West Bengal', postOffice: 'Burrabazar' },
  '700013': { city: 'Kolkata', state: 'West Bengal', postOffice: 'Entally' },
  '700017': { city: 'Kolkata', state: 'West Bengal', postOffice: 'Ballygunge' },
  '700019': { city: 'Kolkata', state: 'West Bengal', postOffice: 'Alipore' },
  '700020': { city: 'Kolkata', state: 'West Bengal', postOffice: 'Bhowanipore' },
  '700026': { city: 'Kolkata', state: 'West Bengal', postOffice: 'Tollygunge' },
  '700029': { city: 'Kolkata', state: 'West Bengal', postOffice: 'Jadavpur' },
  '700031': { city: 'Kolkata', state: 'West Bengal', postOffice: 'Behala' },
  '700032': { city: 'Kolkata', state: 'West Bengal', postOffice: 'Regent Park' },
  '700040': { city: 'Kolkata', state: 'West Bengal', postOffice: 'Lake Town' },
  '700054': { city: 'Kolkata', state: 'West Bengal', postOffice: 'Kasba' },
  '700064': { city: 'Kolkata', state: 'West Bengal', postOffice: 'Gariahat' },
  '700091': { city: 'Kolkata', state: 'West Bengal', postOffice: 'Baguiati' },
  '700106': { city: 'Kolkata', state: 'West Bengal', postOffice: 'New Town' },

  // Ahmedabad, Gujarat
  '380001': { city: 'Ahmedabad', state: 'Gujarat', postOffice: 'Ahmedabad GPO' },
  '380004': { city: 'Ahmedabad', state: 'Gujarat', postOffice: 'Navrangpura' },
  '380006': { city: 'Ahmedabad', state: 'Gujarat', postOffice: 'Paldi' },
  '380007': { city: 'Ahmedabad', state: 'Gujarat', postOffice: 'Maninagar' },
  '380008': { city: 'Ahmedabad', state: 'Gujarat', postOffice: 'Amraiwadi' },
  '380009': { city: 'Ahmedabad', state: 'Gujarat', postOffice: 'Bapunagar' },
  '380013': { city: 'Ahmedabad', state: 'Gujarat', postOffice: 'Naranpura' },
  '380015': { city: 'Ahmedabad', state: 'Gujarat', postOffice: 'Satellite' },
  '380051': { city: 'Ahmedabad', state: 'Gujarat', postOffice: 'Bopal' },
  '380059': { city: 'Ahmedabad', state: 'Gujarat', postOffice: 'Science City' },

  // Jaipur, Rajasthan
  '302001': { city: 'Jaipur', state: 'Rajasthan', postOffice: 'Jaipur GPO' },
  '302002': { city: 'Jaipur', state: 'Rajasthan', postOffice: 'Bani Park' },
  '302003': { city: 'Jaipur', state: 'Rajasthan', postOffice: 'Jawahar Nagar' },
  '302004': { city: 'Jaipur', state: 'Rajasthan', postOffice: 'Raja Park' },
  '302006': { city: 'Jaipur', state: 'Rajasthan', postOffice: 'Sanganer' },
  '302011': { city: 'Jaipur', state: 'Rajasthan', postOffice: 'Mansarovar' },
  '302015': { city: 'Jaipur', state: 'Rajasthan', postOffice: 'Vaishali Nagar' },
  '302017': { city: 'Jaipur', state: 'Rajasthan', postOffice: 'Malviya Nagar' },
  '302018': { city: 'Jaipur', state: 'Rajasthan', postOffice: 'C-Scheme' },
  '302019': { city: 'Jaipur', state: 'Rajasthan', postOffice: 'Tonk Road' },
  '302020': { city: 'Jaipur', state: 'Rajasthan', postOffice: 'Sitapura' },
  '302021': { city: 'Jaipur', state: 'Rajasthan', postOffice: 'Pratap Nagar' },

  // Lucknow, Uttar Pradesh
  '226001': { city: 'Lucknow', state: 'Uttar Pradesh', postOffice: 'Lucknow GPO' },
  '226002': { city: 'Lucknow', state: 'Uttar Pradesh', postOffice: 'Hazratganj' },
  '226003': { city: 'Lucknow', state: 'Uttar Pradesh', postOffice: 'Aminabad' },
  '226004': { city: 'Lucknow', state: 'Uttar Pradesh', postOffice: 'Chowk' },
  '226005': { city: 'Lucknow', state: 'Uttar Pradesh', postOffice: 'Aishbagh' },
  '226010': { city: 'Lucknow', state: 'Uttar Pradesh', postOffice: 'Indira Nagar' },
  '226012': { city: 'Lucknow', state: 'Uttar Pradesh', postOffice: 'Gomti Nagar' },
  '226016': { city: 'Lucknow', state: 'Uttar Pradesh', postOffice: 'Alambagh' },
  '226022': { city: 'Lucknow', state: 'Uttar Pradesh', postOffice: 'Faizabad Road' },

  // Chandigarh
  '160001': { city: 'Chandigarh', state: 'Chandigarh', postOffice: 'Chandigarh GPO' },
  '160002': { city: 'Chandigarh', state: 'Chandigarh', postOffice: 'Sector 17' },
  '160003': { city: 'Chandigarh', state: 'Chandigarh', postOffice: 'Sector 15' },
  '160014': { city: 'Chandigarh', state: 'Chandigarh', postOffice: 'Sector 34' },
  '160015': { city: 'Chandigarh', state: 'Chandigarh', postOffice: 'Sector 45' },
  '160022': { city: 'Chandigarh', state: 'Chandigarh', postOffice: 'Industrial Area Phase 1' },
  '160047': { city: 'Chandigarh', state: 'Chandigarh', postOffice: 'Manimajra' },

  // Bhopal, Madhya Pradesh
  '462001': { city: 'Bhopal', state: 'Madhya Pradesh', postOffice: 'Bhopal GPO' },
  '462002': { city: 'Bhopal', state: 'Madhya Pradesh', postOffice: 'Hamidia Road' },
  '462003': { city: 'Bhopal', state: 'Madhya Pradesh', postOffice: 'Bhopal City' },
  '462010': { city: 'Bhopal', state: 'Madhya Pradesh', postOffice: 'Hoshangabad Road' },
  '462011': { city: 'Bhopal', state: 'Madhya Pradesh', postOffice: 'BHEL Township' },
  '462016': { city: 'Bhopal', state: 'Madhya Pradesh', postOffice: 'Arera Colony' },
  '462026': { city: 'Bhopal', state: 'Madhya Pradesh', postOffice: 'TT Nagar' },

  // Patna, Bihar
  '800001': { city: 'Patna', state: 'Bihar', postOffice: 'Patna GPO' },
  '800004': { city: 'Patna', state: 'Bihar', postOffice: 'Patna City' },
  '800006': { city: 'Patna', state: 'Bihar', postOffice: 'Fraser Road' },
  '800007': { city: 'Patna', state: 'Bihar', postOffice: 'Boring Road' },
  '800013': { city: 'Patna', state: 'Bihar', postOffice: 'Kankarbagh' },
  '800014': { city: 'Patna', state: 'Bihar', postOffice: 'Rajendra Nagar' },
  '800020': { city: 'Patna', state: 'Bihar', postOffice: 'Bailey Road' },

  // Kochi, Kerala
  '682001': { city: 'Kochi', state: 'Kerala', postOffice: 'Ernakulam North' },
  '682002': { city: 'Kochi', state: 'Kerala', postOffice: 'Ernakulam South' },
  '682011': { city: 'Kochi', state: 'Kerala', postOffice: 'Fort Kochi' },
  '682014': { city: 'Kochi', state: 'Kerala', postOffice: 'Mattancherry' },
  '682016': { city: 'Kochi', state: 'Kerala', postOffice: 'Kakkanad' },
  '682017': { city: 'Kochi', state: 'Kerala', postOffice: 'Vyttila' },
  '682019': { city: 'Kochi', state: 'Kerala', postOffice: 'Edapally' },
  '682020': { city: 'Kochi', state: 'Kerala', postOffice: 'Aluva' },
  '682025': { city: 'Kochi', state: 'Kerala', postOffice: 'Info Park' },
  '682030': { city: 'Kochi', state: 'Kerala', postOffice: 'Kaloor' },

  // Nagpur, Maharashtra
  '440001': { city: 'Nagpur', state: 'Maharashtra', postOffice: 'Nagpur GPO' },
  '440002': { city: 'Nagpur', state: 'Maharashtra', postOffice: 'Sadar' },
  '440003': { city: 'Nagpur', state: 'Maharashtra', postOffice: 'Dharampeth' },
  '440010': { city: 'Nagpur', state: 'Maharashtra', postOffice: 'Sitabuldi' },
  '440012': { city: 'Nagpur', state: 'Maharashtra', postOffice: 'Mahal' },
  '440015': { city: 'Nagpur', state: 'Maharashtra', postOffice: 'Manewada' },
  '440022': { city: 'Nagpur', state: 'Maharashtra', postOffice: 'Wardha Road' },

  // Surat, Gujarat
  '395001': { city: 'Surat', state: 'Gujarat', postOffice: 'Surat City' },
  '395002': { city: 'Surat', state: 'Gujarat', postOffice: 'Nanpura' },
  '395003': { city: 'Surat', state: 'Gujarat', postOffice: 'Rander' },
  '395004': { city: 'Surat', state: 'Gujarat', postOffice: 'Udhna' },
  '395005': { city: 'Surat', state: 'Gujarat', postOffice: 'Piplod' },
  '395007': { city: 'Surat', state: 'Gujarat', postOffice: 'Athwalines' },
  '395009': { city: 'Surat', state: 'Gujarat', postOffice: 'Adajan' },
  '395010': { city: 'Surat', state: 'Gujarat', postOffice: 'Vesu' },

  // Indore, Madhya Pradesh
  '452001': { city: 'Indore', state: 'Madhya Pradesh', postOffice: 'Indore GPO' },
  '452002': { city: 'Indore', state: 'Madhya Pradesh', postOffice: 'Rajwada' },
  '452003': { city: 'Indore', state: 'Madhya Pradesh', postOffice: 'M G Road' },
  '452009': { city: 'Indore', state: 'Madhya Pradesh', postOffice: 'Vijay Nagar' },
  '452010': { city: 'Indore', state: 'Madhya Pradesh', postOffice: 'Scheme 54' },
  '452011': { city: 'Indore', state: 'Madhya Pradesh', postOffice: 'Palasia' },
  '452013': { city: 'Indore', state: 'Madhya Pradesh', postOffice: 'Dewas Naka' },
  '452014': { city: 'Indore', state: 'Madhya Pradesh', postOffice: 'LIG' },

  // Noida, Uttar Pradesh
  '201301': { city: 'Noida', state: 'Uttar Pradesh', postOffice: 'Noida Sector 1' },
  '201303': { city: 'Noida', state: 'Uttar Pradesh', postOffice: 'Noida Sector 27' },
  '201304': { city: 'Noida', state: 'Uttar Pradesh', postOffice: 'Noida Sector 44' },
  '201306': { city: 'Noida', state: 'Uttar Pradesh', postOffice: 'Noida Sector 62' },
  '201309': { city: 'Noida', state: 'Uttar Pradesh', postOffice: 'Greater Noida' },
  '201310': { city: 'Noida', state: 'Uttar Pradesh', postOffice: 'Greater Noida West' },

  // Gurugram, Haryana
  '122001': { city: 'Gurugram', state: 'Haryana', postOffice: 'Gurgaon' },
  '122002': { city: 'Gurugram', state: 'Haryana', postOffice: 'DLF Phase 1' },
  '122003': { city: 'Gurugram', state: 'Haryana', postOffice: 'Sushant Lok' },
  '122006': { city: 'Gurugram', state: 'Haryana', postOffice: 'South City' },
  '122009': { city: 'Gurugram', state: 'Haryana', postOffice: 'Sector 49' },
  '122010': { city: 'Gurugram', state: 'Haryana', postOffice: 'Palam Vihar' },
  '122015': { city: 'Gurugram', state: 'Haryana', postOffice: 'Manesar' },
  '122016': { city: 'Gurugram', state: 'Haryana', postOffice: 'Sector 56' },
  '122018': { city: 'Gurugram', state: 'Haryana', postOffice: 'Vatika City' },

  // Coimbatore, Tamil Nadu
  '641001': { city: 'Coimbatore', state: 'Tamil Nadu', postOffice: 'Coimbatore GPO' },
  '641002': { city: 'Coimbatore', state: 'Tamil Nadu', postOffice: 'Gandhipuram' },
  '641004': { city: 'Coimbatore', state: 'Tamil Nadu', postOffice: 'R S Puram' },
  '641006': { city: 'Coimbatore', state: 'Tamil Nadu', postOffice: 'Peelamedu' },
  '641014': { city: 'Coimbatore', state: 'Tamil Nadu', postOffice: 'Saibaba Colony' },
  '641018': { city: 'Coimbatore', state: 'Tamil Nadu', postOffice: 'Singanallur' },

  // Visakhapatnam, Andhra Pradesh
  '530001': { city: 'Visakhapatnam', state: 'Andhra Pradesh', postOffice: 'Visakhapatnam GPO' },
  '530002': { city: 'Visakhapatnam', state: 'Andhra Pradesh', postOffice: 'Seethammadhara' },
  '530003': { city: 'Visakhapatnam', state: 'Andhra Pradesh', postOffice: 'Dwaraka Nagar' },
  '530013': { city: 'Visakhapatnam', state: 'Andhra Pradesh', postOffice: 'Gajuwaka' },
  '530016': { city: 'Visakhapatnam', state: 'Andhra Pradesh', postOffice: 'MVP Colony' },
  '530017': { city: 'Visakhapatnam', state: 'Andhra Pradesh', postOffice: 'Madhurawada' },
  '530045': { city: 'Visakhapatnam', state: 'Andhra Pradesh', postOffice: 'Rushikonda' },

  // Thiruvananthapuram, Kerala
  '695001': { city: 'Thiruvananthapuram', state: 'Kerala', postOffice: 'Thiruvananthapuram GPO' },
  '695003': { city: 'Thiruvananthapuram', state: 'Kerala', postOffice: 'Palayam' },
  '695004': { city: 'Thiruvananthapuram', state: 'Kerala', postOffice: 'Vazhuthacaud' },
  '695007': { city: 'Thiruvananthapuram', state: 'Kerala', postOffice: 'Pattom' },
  '695010': { city: 'Thiruvananthapuram', state: 'Kerala', postOffice: 'Kazhakuttam' },
  '695016': { city: 'Thiruvananthapuram', state: 'Kerala', postOffice: 'Technopark' },

  // Mysuru, Karnataka
  '570001': { city: 'Mysuru', state: 'Karnataka', postOffice: 'Mysuru GPO' },
  '570002': { city: 'Mysuru', state: 'Karnataka', postOffice: 'Lakshmipuram' },
  '570009': { city: 'Mysuru', state: 'Karnataka', postOffice: 'Vijayanagar' },
  '570010': { city: 'Mysuru', state: 'Karnataka', postOffice: 'Hebbal' },
  '570016': { city: 'Mysuru', state: 'Karnataka', postOffice: 'Chamundipuram' },
  '570017': { city: 'Mysuru', state: 'Karnataka', postOffice: 'Jayalakshmipuram' },

  // Amritsar, Punjab
  '143001': { city: 'Amritsar', state: 'Punjab', postOffice: 'Amritsar GPO' },
  '143002': { city: 'Amritsar', state: 'Punjab', postOffice: 'Lawrence Road' },
  '143006': { city: 'Amritsar', state: 'Punjab', postOffice: 'Ranjit Avenue' },
  '143008': { city: 'Amritsar', state: 'Punjab', postOffice: 'Majitha Road' },

  // Guwahati, Assam
  '781001': { city: 'Guwahati', state: 'Assam', postOffice: 'Guwahati GPO' },
  '781003': { city: 'Guwahati', state: 'Assam', postOffice: 'Paltan Bazar' },
  '781005': { city: 'Guwahati', state: 'Assam', postOffice: 'Kachari' },
  '781007': { city: 'Guwahati', state: 'Assam', postOffice: 'Bharalumukh' },
  '781010': { city: 'Guwahati', state: 'Assam', postOffice: 'Ganeshguri' },
  '781019': { city: 'Guwahati', state: 'Assam', postOffice: 'Beltola' },
  '781028': { city: 'Guwahati', state: 'Assam', postOffice: 'IIT Guwahati' },

  // Bhubaneswar, Odisha
  '751001': { city: 'Bhubaneswar', state: 'Odisha', postOffice: 'Bhubaneswar GPO' },
  '751002': { city: 'Bhubaneswar', state: 'Odisha', postOffice: 'Kharvel Nagar' },
  '751009': { city: 'Bhubaneswar', state: 'Odisha', postOffice: 'Saheed Nagar' },
  '751010': { city: 'Bhubaneswar', state: 'Odisha', postOffice: 'Nayapalli' },
  '751013': { city: 'Bhubaneswar', state: 'Odisha', postOffice: 'Acharya Vihar' },
  '751014': { city: 'Bhubaneswar', state: 'Odisha', postOffice: 'Jayadev Vihar' },
  '751024': { city: 'Bhubaneswar', state: 'Odisha', postOffice: 'Infocity' },

  // Ranchi, Jharkhand
  '834001': { city: 'Ranchi', state: 'Jharkhand', postOffice: 'Ranchi GPO' },
  '834002': { city: 'Ranchi', state: 'Jharkhand', postOffice: 'Hinoo' },
  '834003': { city: 'Ranchi', state: 'Jharkhand', postOffice: 'Doranda' },
  '834004': { city: 'Ranchi', state: 'Jharkhand', postOffice: 'Harmu' },
  '834009': { city: 'Ranchi', state: 'Jharkhand', postOffice: 'Kanke Road' },
}

export function lookupPinCode(pinCode: string): PinCodeEntry | null {
  return PIN_CODE_DATA[pinCode] ?? null
}
